name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete"
      - name: Step 2
        run: echo "Step 2 complete"    
  job2:
     needs: job1
     runs-on: ubuntu-latest
     steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: "SOME TEXT"
          # Color of your cow
          color: "BLACK"
          
